import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { esES } from '@clerk/localizations'
import { dark } from '@clerk/themes'

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={esES} appearance={{ baseTheme: dark }}>
      <html lang="es" className="dark" style={{ colorScheme: "dark" }}>
        <body className={`${montserrat.variable} antialiased`}>
          {children}
          <Toaster position="top-right" richColors />
        </body>
      </html>
    </ClerkProvider>
      
  );
}
